# db.yaml

DB:
  default:
    driver: "mysql"
    user: "root"
    password: ""
    host: "localhost"
    port: 3306
    dbname: "english_learn_api"

SERVER:
  port: 8080

APP_STRUCTURE:
  repo: "/internal/repo"
  service: "/internal/service"
